# Generated by Django 5.2.3 on 2025-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('sobre', 'Sobre'), ('header', 'Header'), ('footer', 'Footer'), ('inicio', 'Início')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('texto', models.TextField(blank=True)),
                ('imagem_header', models.ImageField(blank=True, null=True, upload_to='conteudo_site/')),
            ],
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='conteudo',
            new_name='texto',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='postagens/'),
        ),
    ]
