# Generated by Django 5.2.3 on 2025-07-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_conteudosite_rename_conteudo_postagem_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_desenvolvedor', models.CharField(max_length=100, verbose_name='Nome do Desenvolvedor')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('redes_sociais', models.JSONField(blank=True, default=list, verbose_name='Redes Sociais')),
            ],
        ),
        migrations.AlterField(
            model_name='conteudosite',
            name='pagina',
            field=models.CharField(choices=[('sobre', 'Sobre'), ('header', 'Header'), ('inicio', 'Início')], max_length=20, unique=True),
        ),
    ]
