# Generated by Django 5.2.3 on 2025-07-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_footerconfig_alter_conteudosite_pagina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterConfig',
        ),
    ]
