# Generated by Django 5.2.3 on 2025-07-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_footerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do site')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('texto_principal', models.TextField(blank=True, verbose_name='Texto principal')),
                ('imagem_header', models.ImageField(blank=True, null=True, upload_to='conteudo_site/', verbose_name='Imagem do header')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Banner')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('x', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('copyright', models.CharField(default='Seu Nome', max_length=100, verbose_name='Copyright')),
                ('ano', models.PositiveIntegerField(default=2025, verbose_name='Ano')),
            ],
        ),
        migrations.DeleteModel(
            name='ConteudoSite',
        ),
    ]
