# Generated by Django 5.2.3 on 2025-07-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_delete_conteudosite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('inicio', 'Início'), ('sobre', 'Sobre')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('texto', models.TextField(blank=True)),
                ('imagem_header', models.ImageField(blank=True, null=True, upload_to='banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imagem_header',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='texto_principal',
        ),
    ]
