# Generated by Django 5.2.3 on 2025-07-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateTimeField(verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Em Andamento', 'Em andamento')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
    ]
