# Generated by Django 5.2.3 on 2025-07-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tarefa_nome_alter_tarefa_prazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(verbose_name='Prazo'),
        ),
    ]
